name: Playwaright Tests #name of the project

on: # when dis pipline will run
  push:
    bracnhes: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest # which OS will run
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:  # sequence of steps the job will follow
      - name: Checkout repository # name of the step
        uses: actions/checkout@v4 # the action the step gona take
      - name: Say hello
        run: echo hello pts
      - name: Run tests
        run: |
          echo "Start the shopping store application"
          chmod +x ./shopping-store-linux-amd64
          ./shopping-store-linux-amd64 &
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run playwright"
          npm run test:ci

